### PR TITLE
Add to signUp action additional and custom attributes

### PR DESCRIPTION
**Pull request by daaru00**
I tried to re-compile it but I receiving an error during the module inclusion:
```
 ERROR  Failed to compile with 1 errors                                                                                                                                              21:44:20

 error  in ./node_modules/amazon-cognito-vuex-module/dist/index.js

Module parse failed: Unexpected token (15:73535)
You may need an appropriate loader to handle this file type.
```
This is related to the usage of spread operator in [src/mutations.js](https://github.com/Botre/amazon-cognito-vuex-module/blob/master/src/mutations.js#L10), so I can't build, include or test it.

I think some build/contribution information are missing, FYI I'm using Linux with node v9.5.0.

### CODE REVIEW

**Comment by Botre** [comment]
Thx for the pull,

The script to build is **npm run build**.

Is there a reason for the following naming pattern: `custom:${key}`? 
I tried to simplify your proposed implementation a bit, would the following still suit your needs or am I missing something?

 ```
 /* Sign up a new user for a given email and password (then sends registration verification code) */
  signUp({ commit, state }, payload) {
    const email = payload.email;
    const password = payload.password;
    const custom = payload.custom;
    return new Promise((resolve, reject) => {
      const attributes = [
        new CognitoUserAttribute({
          Name: 'email',
          Value: email
        })
      ];
      if (custom) {
        Object.keys(custom).map(key => {
          attributes.push(
            new CognitoUserAttribute({
              Name: `custom:${key}`,
              Value: custom[key]
            })
          );
        });
      }
      state.pool.signUp(email, password, attributes, null, (error, result) => {
        if (error) {
          reject(error);
        } else {
          const user = result.user;
          resolve(user);
        }
      });
    });
  },
```

Thx for contributing.

**Comment by daaru00** [comment]
>The script to build is npm run build.

yep, I used it without problems. The error showed up when I try to include in my Vue app.

>Is there a reason for the following naming pattern: custom:${key}?

Is necessary for custom attributes, refer to [AWS doc](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html#user-pool-settings-custom-attributes)
```
Note: In your code and in rules settings for Role-Based Access Control, 
custom attributes require the custom: prefix to distinguish them from standard attributes. 
```

> I tried to simplify your proposed implementation a bit, would the following still suit your needs or am I missing something?

You miss the other standard Cognito attribute like address, birthdate, family_name, gender.. With my code I try to cover all the cases like:
```javascript
{
  'email': 'example.com',
  'password': 'secret',
  'address': 'London',
  'gender': 'male',
  'custom': {
     'company': 'MyCompany'
   }
}
```

**Comment by Botre** [comment]
Awesome, thanks for clearing that up!
What do you think about an (optional) attributes field with support for a custom field?

```
{
  'email': 'example.com',
  'password': 'secret',
  'attributes': {
      'address': 'London',
      'gender': 'male',
      'custom': {
          'company': 'MyCompany'
      }
  }
}
```

Hard to help you out on the build error without knowing your webpack / babel setup.

Cheers,

**Comment by daaru00** [comment]
> What do you think about an (optional) attributes field with support for a custom field?
It seems clean and well done :+1:

**Comment by Botre** [comment]
Will be part of v2

**Pull request closed without merging**
